### ISSUE TITLE
command flags

### ISSUE THREAD

**Issue by neptalu0** [loloToster/Kaseciak#2]
how do i properly use tha flash associated with the command e.g. play.

play has -n and -nytm flag. how do i use it

**Comment by loloToster** [comment]
To use them you have to put the flag at the end of the song/playlist title. For example:
`/play song title -n`

`-n` - adds the song as next in queue
`-nytm` - skips the YouTube Music search and goes with default `discord-player` search

I am planning on removing the flags because it adds unnecessary complexity. The `-n` flag will probably be replaced with `playnext` command and the `-nytm` flag with `searchengine` command that sets the preferred search engine for specific user.
